version: "2"

services:

  ftp1:
    build: .
    ports:
      - "21:21"
      - "20:20"
      - "10090-10100:10090-10100"
    hostname: ftp1
    volumes:
     - ./logs:/var/log/vsftpd/
     - ./conf/vsftpd.conf:/etc/vsftpd.conf
     - ./conf/vsftpd.userlist:/etc/vsftpd.userlist
     - ./conf/vsftpd.chroot_list:/etc/vsftpd.chroot_list
    networks:
     - lab4
    restart: always

  host:
    build: .
    expose:
      - "1-65535"
    hostname: host
    networks:
      - lab4
    restart: always

networks:
  lab4:
    driver: bridge