version: "2"

services:

  zone08.edu:
    build: .
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    hostname: zone08.edu
    environment:
      - myhostname=zone08.edu
      - mydestination=zone08.edu
      - networks=127.0.0.0/8,[::1]/128,192.168.33.1,192.168.33.2,192.168.33.3,192.168.33.4,192.168.33.5
      - user=<user>@gmail.com #TODO
      - pass=<pass> #TODO
    networks:
      lab2:
        ipv4_address: 192.168.33.1 # If the host ip address is 192.168.X.X then this will not work. Comment networks section and restart. Use only one zone08.edu container.

  host:
    build: .
    environment:
      - myhostname=fake
      - mydestination=fake
      - user=fake@gmail.com
      - pass=fake
    networks:
      lab2:
        ipv4_address: 192.168.33.6

networks:
  lab2:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.33.0/8
